version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
        environment:
          - RAILS_ENV: test
          - POSTGRES_USER: circleci
          - POSTGRES_DB: circle_test
          - BUNDLER_VERSION: 2.0.2
      - image: circleci/postgres:9.6-alpine
        environment:
          - POSTGRES_USER: circleci
          - POSTGRES_DB: circle_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem update bundler && bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:schema:load
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  documentation:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            npm install -g apidoc
            npm install -g @forfuture/apidoc-openapi
      - run:
          command: |
            apidoc -i app/ -o doc/apidoc/
            apidoc-openapi --project ./apidoc.json --src app/ --out ./doc/openapi.json
      - persist_to_workspace:
          root: "."
          paths: doc/*
  docs-deploy:
    docker:
      - image: circleci/node:10.15-browsers
    steps:
      - checkout
      - attach_workspace:
          at: doc/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "circleci@mikamai.com"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist doc/

workflows:
  version: 2
  build:
    jobs:
      - test
      - documentation:
          filters:
            branches:
              only:
                - not # desactivated for now
      - docs-deploy:
          requires:
            - test
            - documentation
          filters:
            branches:
              only:
                - not # desactivated for now

